#!/bin/sh
#loading view
GN='\033[42;32m+\033[0m';
GR='\033[47;37m+\033[0m';
RD='\033[45;35m+\033[0m';
splashimg="\
-----------------------------------\n\
-----------------------------------\n\
---*****-*---*-*****-*-----*-------\n\
---*-----*---*-*-----*-----*-------\n\
---*****-*****-*****-*-----*-------\n\
-------*-*---*-*-----*-----*-------\n\
---*****-*---*-*****-*****-*****---\n\
-----------------------------------\n\
---*****---*-------*****---*****---\n\
---*-------*-------*---*-----*-----\n\
---*****---*-------*---*-----*-----\n\
-------*---*-------*---*-----*-----\n\
---*****---*****---*****-----*-----\n\
-----------------------------------\n\
-----------------------------------"

splashimg=${splashimg//-/"$GR"};
splashimg=${splashimg//'*'/"$GN"};

homeimg="\
-----------------------------------\n\
-----------------------------------\n\
-----------------------------------\n\
-----*******--*******--*******-----\n\
-----*******--*******--*******-----\n\
-----*******--*******--*******-----\n\
-----*******--*******--*******-----\n\
-----*******--*******--*******-----\n\
-----*******--*******--*******-----\n\
-----*******--*******--*******-----\n\
-----------------------------------\n\
-----------------------------------\n\
-----------------------------------\n\
-----------------------------------\n\
-----------------------------------"
homeimg=${homeimg//-/"$GR"}
homeimg=${homeimg//'*'/"$GN"}

function waitForKey(){
    read -n 1;
}

function showsplash(){
   tput cup 0 0;
   printf "$splashimg";
}

function enterHome(){
    tput cup 0 0;
    printf "$homeimg"
}

declare zro;
declare one;
declare two;
declare thr;

zro=("*****" "*---*" "*---*" "*---*" "*****")
for i in {0..4};do
    zro[$i]=${zro[$i]//-/"$GN"}
    zro[$i]=${zro[$i]//'*'/"$GR"}
done;

one=(--**- -***- --**- --**- -****);
for i in {0..4};do
   one[$i]=${one[$i]//-/"$GN"};
   one[$i]=${one[$i]//'*'/"$GR"};
done;

two=("*****" "----*" "*****" "*----" "*****");
for i in {0..4};do
   two[$i]=${two[$i]//-/"$GN"};
   two[$i]=${two[$i]//'*'/"$GR"};
done;

thr=("*****" "----*" "*****" "----*" "*****");
for i in {0..4};do
    thr[$i]=${thr[$i]//-/"$GN"};
    thr[$i]=${thr[$i]//'*'/"$GR"};
done;

x=4;
y[1]=6;y[2]=15;y[3]=24;
function putnum(){
   oy=${y[$1]};
   format='printf ${%s[%d]}';
   if [[ 0 == $2 ]]; then
       con=zro;
   elif [[ 1 == $2 ]]; then
       con=one;
   elif [[ 2 == $2 ]]; then
       con=two;
   elif [[ 3 == $2 ]]; then
       con=thr;
   fi
   for i in {0..4};do
      tput cup $((x+i)) $oy;
      printf -v cmd "$format" $con $i;
      #echo "llll $con"
      eval "$cmd"
   done;
}

function roll(){
   case $1 in
      1)col=6;;
      2)col=15;;
      3)col=24;;
   esac;
   
   for name in zro one two thr;do
      for i in {1..4};do
         row=4;
         for ((j=4-i;j<5;j++));do
              tput cup $((row++)) $col;
              printf -v cmd "printf \${%s[$j]}" $name;
              eval $cmd;
          done;
          sleep 0.05;
       done;
   done;
}

declare icon;
function spinAction(){
   a=$1;
   icon[1]=$((a/16));
   ((a-=(icon[1])*16));
   icon[2]=$((a/4));
   icon[3]=$((a%4));
   roll 1
   putnum 1 ${icon[1]};
   sleep 0.03
   roll 2
   putnum 2 ${icon[2]};
   sleep 0.03;
   roll 3
   putnum 3 ${icon[3]}
}

declare result
function resultcheck(){
   if [[ $1 == $2 && $2 == $3 ]]; then
       result=true;
   else
       result=false;
   fi
}

function clearcyc(){
    tput cup 1 3;
    printf "\033[47;37m+++++++++++++++++++++++++++++\033[0m";
    for i in {2..11};do
       tput cup $i 3;printf $GR;tput cup $i 31;printf $GR;
    done;
    tput cup 12 3;
    printf "\033[47;37m+++++++++++++++++++++++++++++\033[0m"; 
}

function showcyc(){
    tput cup 1 3;
    printf "\033[45;35m+++++++++++++++++++++++++++++\033[0m";
    for i in {2..11};do
       tput cup $i 3;printf $RD;tput cup $i 31;printf $RD;
    done;
    tput cup 12 3;
    printf "\033[45;35m+++++++++++++++++++++++++++++\033[0m"; 
}

function runcycleline(){
    declare count;
    while [ $((count++)) -lt 3 ]; do
        tput cup 15 0;
        showcyc;
        sleep 0.5;
        clearcyc;
        sleep 0.5;        
    done;
}

function putwin(){
    tput cup 
}

tput clear;
showsplash;
waitForKey;
enterHome;
while true;do
   read -n 1 key;
   if [[ "e" == $key ]];then
       tput cup 15 0;
       break;
   fi
   r=$((RANDOM%64));
   spinAction $r;
   resultcheck ${icon[1]} ${icon[2]} ${icon[3]};
   if [[ "$result" == "true" ]];then
       tput cup 15 0;
       echo "you are win! ";
       runcycleline;
       tput cup 16 0;echo "touch enter to contiue";
   else
       tput cup 15 0;
       echo "you are lost!";
   fi
done;

#why need exit
exit 0;
